export interface ToolNames {
    PENCIL_TOOL_NAME: string;
    PEN_TOOL_NAME: string;
    BRUSH_TOOL_NAME: string;
    SPRAY_TOOL_NAME: string;
    SQUARE_TOOL_NAME: string;
    CIRCLE_TOOL_NAME: string;
    LINE_TOOL_NAME: string;
    FILL_TOOL_NAME: string;
    ERASER_TOOL_NAME: string;
    SQUARE_SELECTION_TOOL_NAME: string;
    CIRCLE_SELECTION_TOOL_NAME: string;
    PIPETTE_TOOL_NAME: string;
    POLYGONE_TOOL_NAME: string;
    STAMP_TOOL_NAME: string;
}

export const TOOL_NAMES: ToolNames = {
    PENCIL_TOOL_NAME: 'Crayon',
    PEN_TOOL_NAME: 'Plume',
    BRUSH_TOOL_NAME: 'Pinceau',
    SPRAY_TOOL_NAME: 'Aérosol',
    SQUARE_TOOL_NAME: 'Rectangle',
    CIRCLE_TOOL_NAME: 'Ellipse',
    LINE_TOOL_NAME: 'Ligne',
    FILL_TOOL_NAME: 'Sceau',
    ERASER_TOOL_NAME: 'Efface',
    SQUARE_SELECTION_TOOL_NAME: 'Sélection - Rectangle',
    CIRCLE_SELECTION_TOOL_NAME: 'Sélection - Ellipse',
    PIPETTE_TOOL_NAME: 'Pipette',
    POLYGONE_TOOL_NAME: 'Polygone',
    STAMP_TOOL_NAME: 'Étampe',
};

export const TOOL_NAMES_ARRAY: string[] = [
    TOOL_NAMES.PENCIL_TOOL_NAME,
    TOOL_NAMES.PEN_TOOL_NAME,
    TOOL_NAMES.BRUSH_TOOL_NAME,
    TOOL_NAMES.SPRAY_TOOL_NAME,
    TOOL_NAMES.SQUARE_TOOL_NAME,
    TOOL_NAMES.CIRCLE_TOOL_NAME,
    TOOL_NAMES.LINE_TOOL_NAME,
    TOOL_NAMES.FILL_TOOL_NAME,
    TOOL_NAMES.ERASER_TOOL_NAME,
    TOOL_NAMES.PIPETTE_TOOL_NAME,
    TOOL_NAMES.SQUARE_SELECTION_TOOL_NAME,
    TOOL_NAMES.CIRCLE_SELECTION_TOOL_NAME,
    TOOL_NAMES.POLYGONE_TOOL_NAME,
    TOOL_NAMES.STAMP_TOOL_NAME,
];
